
services:
  backend:
    image: pms_backend:latest   
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - pms-network


  frontend:
    image: pms_frontend:latest  
    restart: always
    ports:
      - "4000:80"
    depends_on:
      - backend
    networks:
      - pms-network

  database:
    image: postgres:15-alpine
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pms-network

networks:
  pms-network:
    driver: bridge

volumes:
  db_data:
