FROM node:20-alpine
RUN apk add --no-cache curl
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma/
RUN npx prisma generate

COPY . .
EXPOSE 5000


CMD ["sh", "-c", "npx prisma db push && npm run start"]